name: Test Project Compile
on: [push]
jobs:
  Compile:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      shell: cmd
      run: msbuild /m NEPS.sln /p:Platform=x64 /p:Configuration=Release
